export enum EGroundType {
    ISLAND = "ISLAND",
    ICELAND = "ICELAND",
    DESERTLAND = "DESERTLAND",
    LAVALAND = "LAVALAND",
    CRYSTALLAND = "CRYSTALLAND",
    TOXICLAND = "TOXICLAND",
    WATERLAND = "WATERLAND",
    CRYSTALLAND2 = "CRYSTALLAND2",
    DEADLAND = "DEADLAND",
}
